# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef3cabc7d6827a00c067465a8e658e0003f856d1d2c5fab763cc3703746ed3a476166766698d9003af597753e500bd62466b6064546d62e03fd2b6e0bd735686

test:
  secret_key_base: 719cf5fe5cf53c934596d8bb498d1892d4996ff3acad403a13df2cea0521f356d3596a6619eddce5e310d7cce8acca49e19d6bb369d77b5496bb0f8354449469

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
